### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ericdallo** [pierotofy/set-swap-space#1]
Would be possible? I receive a `free` command not found on a windows runner

**Comment by pierotofy** [comment]
I'm not sure, maybe? Feel free to open a pull request to contribute to this (my goal was to get this to work for Linux runners, so I don't plan to add support for Windows myself).

**Comment by mraible** [comment]
I added an `if` conditional to my action to solve this:

```yaml
    - name: Set up swap space
      if: runner.os == 'Linux'
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 10
```

On Windows, I'm using:

```yaml
      - name: Configure pagefile
        uses: al-cheb/configure-pagefile-action@v1.2

      - name: Set up pagefile
        run: |
          (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
```
