### ISSUE TITLE
Fails with `swapoff: Not superuser` when running inside container

### ISSUE THREAD

**Issue by scottgigante-immunai** [pierotofy/set-swap-space#2]
Running `set-swap-space` on Github Actions with the `container` directive [here](https://github.com/giovp/SingleCellOpenProblems/runs/6494687199?check_suite_focus=true#step:30:44) throws an error about superuser permissions.

MRE:
```
  run_tester:
    runs-on: ubuntu-latest

    container:
      image: singlecellopenproblems/openproblems-github-actions:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp:/tmp
      options: --user root

    steps:

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
```

Traceback:
```
Run pierotofy/set-swap-space@master
  with:
    swap-size-gb: 10
Run echo "Memory and swap:"
  echo "Memory and swap:"
  free -h
  echo
  swapon --show
  echo
  shell: bash --noprofile --norc -e -o pipefail {0}
Memory and swap:
               total        used        free      shared  buff/cache   available
Mem:           6.8Gi       794Mi       953Mi       9.0Mi       5.1Gi       5.7Gi
Swap:          4.0Gi        20Mi       4.0Gi

NAME          TYPE SIZE  USED PRIO
/mnt/swapfile file   4G 20.1M   -2

Run export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
  export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
  sudo swapoff $SWAP_FILE
  sudo rm $SWAP_FILE
  sudo fallocate -l 10G $SWAP_FILE
  sudo chmod 600 $SWAP_FILE
  sudo mkswap $SWAP_FILE
  sudo swapon $SWAP_FILE
  shell: bash --noprofile --norc -e -o pipefail {0}
swapoff: Not superuser.
Error: Process completed with exit code 1[6](https://github.com/giovp/SingleCellOpenProblems/runs/6494687199?check_suite_focus=true#step:11:6).
```
